//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_People                      161
#define IDB_BITMAP3                     163
#define IDB_BITMAP4                     164
#define IDB_Blue                        164
#define IDB_SSSS                        165
#define IDB_BITMAP5                     166
#define IDB_Green                       166
#define IDB_Role1                       171
#define IDB_Role2                       172
#define IDB_Role3                       173
#define IDB_Role4                       174
#define IDB_Role5                       175
#define IDB_Role6                       176
#define IDB_Role0                       177
#define IDB_RoleD2                      183
#define IDB_RoleD3                      184
#define IDB_RoleU1                      185
#define IDB_RoleU2                      186
#define IDB_RoleU3                      187
#define IDB_BITMAP6                     190
#define IDB_ground                      190
#define IDB_Message                     191
#define IDB_GameName                    193
#define IDB_StareBackGround             194
#define IDB_G_gress                     195
#define IDB_G_witer                     196
#define IDB_tree                        197
#define IDB_MakeForm                    198
#define IDB_ItemForm                    200
#define IDB_flint                       201
#define IDB_state_brain                 202
#define IDB_state_hart                  203
#define IDB_state_hunger                204
#define IDB_G_BigGress                  206
#define IDB_Axes                        207
#define IDB_item_Branch                 208
#define IDB_MapHay                      209
#define IDB_item_wood                   210
#define IDB_item_grass                  211
#define IDB_map_branch                  212
#define IDB_item_stone                  213
#define IDB_map_stone                   214
#define IDB_RoleL1                      215
#define IDB_RoleL2                      216
#define IDB_RoleL3                      217
#define IDB_RoleL4                      218
#define IDB_RoleL5                      219
#define IDB_RoleL6                      220
#define IDB_RoleR1                      221
#define IDB_RoleR2                      222
#define IDB_RoleR3                      223
#define IDB_RoleR4                      224
#define IDB_RoleR5                      225
#define IDB_RoleR6                      226
#define IDB_RoleD1                      227
#define IDB_RoleD4                      229
#define IDB_RoleD5                      230
#define IDB_RoleD6                      231
#define IDB_hud_axeYes                  233
#define IDB_hud_axeNo                   234
#define IDB_Role_Axe                    239
#define IDB_Role_Axe_Hack3              240
#define IDB_hud_campfireNo              241
#define IDB_hud_campfireYes             242
#define IDB_hud_torchfireNo             243
#define IDB_hud_torchfireYes            244
#define IDB_Item_Torchfire              245
#define IDB_Role_torchfire              246
#define IDB_item_campfire               247
#define IDB_item_RabbitDead             248
#define IDB_item_Rabbit                 249
#define IDB_face_roast                  250
#define IDB_face_drop                   251
#define IDB_Shadow                      252
#define IDB_Map_rabbitR1                253
#define IDB_Map_rabbitR2                254
#define IDB_Map_rabbitR3                255
#define IDB_Map_rabbitR4                256
#define IDB_Map_rabbitL1                257
#define IDB_Map_rabbitL2                258
#define IDB_Map_rabbitL3                259
#define IDB_Map_rabbitL4                260
#define IDB_Black                       261
#define IDB_blackO                      262
#define IDB_RoleU4                      264
#define IDB_RoleU5                      265
#define IDB_RoleU6                      266
#define IDB_RoleU7                      267
#define IDB_RoleU8                      268
#define IDB_RoleU9                      269
#define IDB_hud_tools                   270
#define IDB_hud_tools_fire              272
#define IDB_item_pickaxe                273
#define IDB_item_spade                  274
#define IDB_text_willsun                275
#define IDB_text_willdark               276
#define IDB_hud_pickaxeYes              277
#define IDB_hud_pickaxeNo               278
#define IDB_hud_spadeYes                279
#define IDB_hud_spadeNo                 280
#define IDB_day1                        281
#define IDB_day2                        285
#define IDB_day3                        286
#define IDB_day4                        287
#define IDB_day5                        288
#define IDB_day6                        289
#define IDB_day7                        290
#define IDB_day8                        291
#define IDB_PauseMenuImg                292
#define IDB_MoribundScrn                293
#define IDB_MoribundScrn2               294
#define IDB_min_Map                     295
#define IDB_PauseButton                 296
#define IDB_BigMapBack                  297
#define IDB_DeadMenu                    298
#define IDB_Role_Axe_Hack1              299
#define IDB_Role_Axe_Hack2              300
#define IDB_map_forest11                302
#define IDB_map_forest12                303
#define IDB_map_forest13                304
#define IDB_map_forest14                305
#define IDB_map_forest15                306
#define IDB_map_forest16                307
#define IDB_map_forest17                308
#define IDB_map_forest18                309
#define IDB_map_forest19                310
#define IDB_Sea                         311
#define IDB_item_Hat                    312
#define IDB_Map_DogwalkL1               313
#define IDB_Map_DogwalkL2               314
#define IDB_Map_DogwalkL3               315
#define IDB_Map_DogwalkR1               316
#define IDB_Map_DogwalkR2               317
#define IDB_Map_DogwalkR3               318
#define IDB_Map_dogL1                   319
#define IDB_Map_dogL2                   320
#define IDB_Map_dogL3                   321
#define IDB_Map_dogL4                   322
#define IDB_Map_dogL5                   323
#define IDB_Map_dogL6                   324
#define IDB_Map_dogL7                   325
#define IDB_Map_dogL8                   326
#define IDB_Map_dogR1                   327
#define IDB_Map_dogR2                   328
#define IDB_Map_dogR3                   329
#define IDB_Map_dogR5                   330
#define IDB_Map_dogR4                   331
#define IDB_Map_dogR6                   332
#define IDB_Map_dogR7                   333
#define IDB_Map_dogR8                   334
#define IDB_Map_DogfightL1              335
#define IDB_Map_DogfightL2              336
#define IDB_Map_DogfightL3              337
#define IDB_Map_DogfightL4              338
#define IDB_Map_DogfightL5              339
#define IDB_Map_DogfightL6              340
#define IDB_Map_DogfightR1              341
#define IDB_Map_DogfightR2              342
#define IDB_Map_DogfightR3              343
#define IDB_Map_DogfightR4              344
#define IDB_Map_DogfightR5              345
#define IDB_Map_DogfightR6              346
#define IDB_item_Carrot                 347
#define IDB_item_gold                   348
#define IDB_item_Honey                  350
#define IDB_item_Berry                  351
#define IDB_TEXT                        352
#define IDB_role_pick1                  354
#define IDB_role_pick2                  355
#define IDB_role_pick3                  356
#define IDB_test                        357
#define IDB_Role_Hat1                   358
#define IDB_Role_Hat2                   359
#define IDB_dayDG                       360
#define IDB_mouse2                      363
#define IDB_mouse1                      364
#define IDB_OverMenu                    365
#define IDB_AllBlock                    366
#define IDB_G_Grass                     367
#define IDB_minMap_fire                 368
#define IDB_minMap_Role                 369
#define IDB_map_Carrot                  370
#define IDB_Role_PickAxe1               371
#define IDB_Role_PickAxe2               372
#define IDB_Role_PickAxe3               373
#define IDB_Role_PickAxe4               374
#define IDB_item_campfire_1             376
#define IDB_explain_left1               377
#define IDB_explain_left2               378
#define IDB_explain_left3               379
#define IDI_ICON1                       383
#define IDB_Role_spade1                 385
#define IDB_Role_spade2                 386
#define IDB_BITMAP7                     387
#define IDB_firstBG                     387
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        388
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
